import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'localization_provider.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'th': {
      'login_title': 'KMUTNB Shuttle Bus',
      'email': 'อีเมล',
      'password': 'รหัสผ่าน',
      'login_btn': 'เข้าสู่ระบบ',
      'no_account': 'ยังไม่มีบัญชีใช่ไหม? สมัครสมาชิกที่นี่',
      'missing_input': 'กรุณากรอกอีเมลและรหัสผ่านให้ครบถ้วน',
      'invalid_login': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
      'register_title': 'สมัครสมาชิก',
      'register_btn': 'สมัครใช้งาน',
      'already_have_account': 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
      'student_role': 'นักศึกษา',
      'driver_role': 'พนักงานขับรถ',
      'settings': 'การตั้งค่า',
      'account': 'บัญชีผู้ใช้',
      'edit_profile': 'แก้ไขข้อมูลส่วนตัว',
      'change_password': 'เปลี่ยนรหัสผ่าน',
      'app_settings': 'ตั้งค่าแอปพลิเคชัน',
      'change_language': 'เปลี่ยนภาษา',
      'dark_mode': 'โหมดกลางคืน (Dark Mode)',
      'logout': 'ออกจากระบบ',
      'map': 'แผนที่',
      'schedule': 'ตารางรถ',
      'report': 'แจ้งปัญหา',
      'driver_status': 'สถานะรถ',
      'ticket_report': 'แจ้งสถานการณ์',
      'notifications': 'แจ้งเตือน',
      'status_ready': 'พร้อมให้บริการ',
      'status_stop': 'หยุดให้บริการ',
      'status_maintain': 'ซ่อมบำรุง',
      'status_fuel': 'เติมน้ำมัน',
      'current_status': 'เลือกสถานะปัจจุบันของรถบัส:',
      'save_status': 'บันทึกสถานะ',
      'status_updated': 'อัปเดตเป็นสถานะ: ',
      'manage_status': 'จัดการสถานะรถ',
      'manage_tickets': 'จัดการสถานการณ์',
      'alert_queue': 'การแจ้งเตือนคิวรถ',
      'remaining_tickets': 'เลือกจำนวนผู้โดยสารบนรถ (ประมาณ)',
      'no_passenger': 'ว่าง (0-10)',
      'some_passenger': 'พอมีที่นั่ง (11-20)',
      'full_passenger': 'เต็ม/แน่น (21+)',
      'save_ticket': 'บันทึกจำนวนคน',
      'ticket_updated': 'บันทึกจำนวนผู้โดยสารเรียบร้อย',
      'exact_passenger_count': 'ระบุจำนวนผู้โดยสาร (ถ้ามี)',
      'enter_exact_passenger': 'กรอกจำนวนคน (เช่น 15)',
    },
    'en': {
      'login_title': 'KMUTNB Shuttle Bus',
      'email': 'Email',
      'password': 'Password',
      'login_btn': 'Login',
      'no_account': 'Don\'t have an account? Register',
      'missing_input': 'Please enter both email and password',
      'invalid_login': 'Invalid email or password',
      'register_title': 'Register',
      'register_btn': 'Sign Up',
      'already_have_account': 'Already have an account? Login',
      'student_role': 'Student',
      'driver_role': 'Driver',
      'settings': 'Settings',
      'account': 'Account',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'app_settings': 'App Settings',
      'change_language': 'Language',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'map': 'Map',
      'schedule': 'Schedule',
      'report': 'Report Issue',
      'driver_status': 'Status',
      'ticket_report': 'Reports',
      'notifications': 'Alerts',
      'status_ready': 'Ready for Service',
      'status_stop': 'Out of Service',
      'status_maintain': 'Maintenance',
      'status_fuel': 'Refueling',
      'current_status': 'Select current bus status:',
      'save_status': 'Save Status',
      'status_updated': 'Status updated to: ',
      'manage_status': 'Manage Bus Status',
      'manage_tickets': 'Manage Situations',
      'alert_queue': 'Queue Alerts',
      'remaining_tickets': 'Select appx. passengers in bus',
      'no_passenger': 'Empty (0-10)',
      'some_passenger': 'Some Seats (11-20)',
      'full_passenger': 'Full (21+)',
      'save_ticket': 'Save Count',
      'ticket_updated': 'Passenger count saved successfully',
      'exact_passenger_count': 'Exact passenger count (optional)',
      'enter_exact_passenger': 'Enter amount (e.g. 15)',
    },
  };

  static String of(BuildContext context, String key) {
    final locale = Provider.of<LocalizationProvider>(
      context,
      listen: true,
    ).locale;
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}
