import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'localization_provider.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'th': {
      'login_title': 'KMUTNB Shuttle Bus',
      'username': 'รหัสนักศึกษา / รหัสพนักงาน',
      'student_id': 'รหัสนักศึกษา',
      'employee_id': 'รหัสพนักงาน',
      'password': 'รหัสผ่าน',
      'login_btn': 'เข้าสู่ระบบ',
      'no_account': 'ยังไม่มีบัญชีใช่ไหม? สมัครสมาชิกที่นี่',
      'missing_input': 'กรุณากรอกรหัสผู้ใช้และรหัสผ่านให้ครบถ้วน',
      'invalid_login': 'รหัสผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
      'register_title': 'สมัครสมาชิก',
      'register_btn': 'ยืนยันการสมัคร',
      'already_have_account': 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
      'student_role': 'นักศึกษา',
      'driver_role': 'พนักงานขับรถ',
      'full_name': 'ชื่อ-นามสกุล',
      'confirm_password': 'ยืนยันรหัสผ่าน',
      'fill_all_fields': 'กรุณากรอกข้อมูลให้ครบถ้วน',
      'password_mismatch': 'รหัสผ่านไม่ตรงกัน',
      'register_success': 'สมัครสมาชิกสำเร็จ!',
      'register_error': 'เกิดข้อผิดพลาดในการสมัครสมาชิก',
      'username_taken': 'รหัสผู้ใช้นี้ถูกใช้งานแล้ว',
      'settings': 'การตั้งค่า',
      'account': 'บัญชีผู้ใช้',
      'edit_profile': 'แก้ไขข้อมูลส่วนตัว',
      'change_password': 'เปลี่ยนรหัสผ่าน',
      'app_settings': 'ตั้งค่าแอปพลิเคชัน',
      'change_language': 'เปลี่ยนภาษา',
      'dark_mode': 'โหมดกลางคืน (Dark Mode)',
      'logout': 'ออกจากระบบ',
      'map': 'แผนที่',
      'map_title': 'ตำแหน่งรถ (แผนที่)',
      'schedule': 'ตารางรถ',
      'schedule_title': 'ตารางเวลาเดินรถ',
      'report': 'แจ้งปัญหา',
      'driver_status': 'สถานะรถ',
      'ticket_report': 'รายงานตั๋ว',
      'notifications': 'แจ้งเตือน',
      'status_ready': 'พร้อมให้บริการ',
      'status_stop': 'หยุดให้บริการ',
      'status_maintain': 'ซ่อมบำรุง',
      'status_fuel': 'เติมน้ำมัน',
      'current_status': 'เลือกสถานะปัจจุบันของรถบัส:',
      'save_status': 'บันทึกสถานะ',
      'status_updated': 'อัปเดตเป็นสถานะ: ',
      'manage_status': 'จัดการสถานะรถ',
      'alert_queue': 'การแจ้งเตือนรอบรถ',
      'remaining_tickets': 'เลือกจำนวนผู้โดยสารบนรถ (ประมาณ)',
      'no_passenger': 'ว่าง (0-10)',
      'some_passenger': 'พอมีที่นั่ง (11-20)',
      'full_passenger': 'เต็ม/แน่น (21+)',
      'save_ticket': 'บันทึกรายงาน',
      'ticket_updated': 'บันทึกรายงานตั๋วเรียบร้อย',
      'exact_passenger_count': 'จำนวนตั๋วโดยสารที่เก็บได้',
      'enter_exact_passenger': 'กรอกจำนวนตั๋ว (เช่น 45)',
      'driver_name_label': 'คนขับ',
      'driver_phone_label': 'เบอร์โทร',
      'license_plate_label': 'ทะเบียน',
      'speed_label': 'ความเร็ว',
      'route_label': 'เส้นทาง',
      'time_label': 'เวลา',
      'bus_label': 'รถบัส',
      'no_schedule': 'ไม่มีข้อมูลตารางเดินรถ',
      'select_round_time': 'เลือกรอบเวลาที่ขับ',
      'select_round_time_hint': 'เลือกรอบเวลา',
      'enter_ticket_count': 'กรุณากรอกจำนวนตั๋ว',
      'invalid_ticket_count': 'จำนวนตั๋วไม่ถูกต้อง',
      'recent_reports': 'รายงานล่าสุด',
      'no_reports': 'ยังไม่มีรายงาน',
      'ticket_count_label': 'จำนวนตั๋ว',
      'round_time_label': 'รอบเวลา',
      'round_passed': 'ผ่านไปแล้ว',
      'time_remaining': 'เหลือเวลา',
      'minutes': 'นาที',
      'hours': 'ชั่วโมง',
      'no_bus_assigned': 'ยังไม่มีรถที่ถูกกำหนดให้',
      'test_notification': 'ทดสอบแจ้งเตือน',
      'test_notification_body': 'นี่คือข้อความแจ้งเตือนทดสอบ',
      'phone': 'เบอร์โทรศัพท์',
      'required_field': 'กรุณากรอกข้อมูล',
      'profile_saved': 'บันทึกข้อมูลเรียบร้อยแล้ว',
      'profile_save_error': 'เกิดข้อผิดพลาดในการบันทึกข้อมูล',
      'save_profile': 'บันทึกข้อมูล',
      'show_all_rounds': 'ดูทุกรอบ',
      'auto_notification_toggle': 'แจ้งเตือนอัตโนมัติ',
      'notification_active_desc':
          'ระบบจะแจ้งเตือนก่อนออกรถ 15 นาที และเมื่อถึงเวลาออกรถ',
      'notification_inactive_desc':
          'เปิดเพื่อรับแจ้งเตือนก่อนถึงรอบรถอัตโนมัติ',
      'notification_info':
          'แจ้งเตือน 2 ครั้ง: ก่อนถึงรอบ 15 นาที และเมื่อถึงเวลาออกรถ',
      'depart_now': 'ออกรถ',
      'status_running': 'กำลังวิ่ง',
      'status_parking': 'จอดอยู่',
      'status_at_stop': 'รับส่งตรงป้าย',
      'status_unknown': 'ไม่ทราบสถานะ',
      'arriving_buses': 'รถที่กำลังจะมาถึง (คลิกเพื่อดูตำแหน่งรถ)',
      'waiting_tracking': 'กำลังรอข้อมูลรถจากระบบติดตาม...',
      'driver': 'คนขับ',
      'driver_phone': 'โทร',
      'license_plate_prefix': 'ทะเบียน',
      'speed_suffix': 'กม./ชม.',
      'sys_status': 'สถานะระบบ',
      'last_updated': 'อัปเดตล่าสุด',
      'live_count': 'LIVE',
      'schedule_header': 'ตารางเวลาวิ่งรถสองแถว',
      'campus_name': 'มจพ. วิทยาเขตปราจีนบุรี',
      'round': 'รอบ',
      'responsible_person': 'ผู้รับผิดชอบ',
      'report_issue_title': 'แจ้งปัญหาการใช้บริการ',
      'issue_topic': 'หัวข้อปัญหา',
      'issue_late': 'รถไม่มาตรงเวลา',
      'issue_driver': 'พฤติกรรมพนักงานขับรถ',
      'issue_app': 'แอปพลิเคชันมีปัญหา',
      'issue_other': 'อื่นๆ',
      'select_issue_hint': 'เลือกปัญหาที่พบ',
      'issue_required': 'กรุณาเลือกหัวข้อปัญหา',
      'additional_details': 'รายละเอียดเพิ่มเติม',
      'details_hint': 'อธิบายปัญหาที่พบเพิ่มเติม...',
      'details_required': 'กรุณากรอกรายละเอียด',
      'submit_report': 'ส่งรายงาน',
      'report_success': 'ส่งรายงานความร้องเรียนสำเร็จ',
      'arrived': 'ถึงแล้ว',
      'will_arrive_in': 'จะถึงภายใน',
      'stop_short_1': 'หอพักฯ',
      'stop_short_2': 'หน้า ม.',
      'stop_short_3': 'บริหารฯ',
      'stop_short_4': 'อุตฯ',
      'stop_short_5': 'อาคาร',
      'stop_short_6': 'เทคโนฯ',
      'stop_short_7': 'วิศวะฯ',
      'stop_full_1': 'หอพักนักศึกษา',
      'stop_full_2': 'หน้ามหาวิทยาลัย',
      'stop_full_3': 'คณะบริหารธุรกิจฯ',
      'stop_full_4': 'คณะอุตสาหกรรมเกษตร',
      'stop_full_5': 'อาคารบริหาร',
      'stop_full_6': 'คณะเทคโนฯ',
      'stop_full_7': 'คณะวิศวะฯ',
      'driver_prefix': 'นาย',
      'phone_label_short': 'โทร.',
      'round_label_short': 'รอบ',
      'next_label_short': 'ถัดไป',
      'error_prefix': 'เกิดข้อผิดพลาด',
      'user_inactive': 'บัญชีนี้ปิดการใช้งาน หรือถูกระงับ',
      'network_error': 'การเชื่อมต่ออินเทอร์เน็ตมีปัญหา',
      'permission_denied': 'ไม่สามารถบันทึกข้อมูลได้ (Permission denied)',
      'view_all_reports': 'ดูรายงานทั้งหมด',
      'show_less_reports': 'แสดงน้อยลง',
      'current_password': 'รหัสผ่านปัจจุบัน',
      'new_password': 'รหัสผ่านใหม่',
      'confirm_new_password': 'ยืนยันรหัสผ่านใหม่',
      'enter_current_password': 'กรุณากรอกรหัสผ่านปัจจุบัน',
      'enter_new_password': 'กรุณากรอกรหัสผ่านใหม่',
      'enter_confirm_password': 'กรุณายืนยันรหัสผ่านใหม่',
      'password_min_length': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
      'password_changed_success': 'เปลี่ยนรหัสผ่านเรียบร้อยแล้ว',
      'password_change_error': 'เกิดข้อผิดพลาดในการเปลี่ยนรหัสผ่าน',
      'incorrect_current_password': 'รหัสผ่านปัจจุบันไม่ถูกต้อง',
      'next_round': 'รอบถัดไป',
    },
    'en': {
      'login_title': 'KMUTNB Shuttle Bus',
      'username': 'Student ID / Employee ID',
      'student_id': 'Student ID',
      'employee_id': 'Employee ID',
      'password': 'Password',
      'login_btn': 'Login',
      'no_account': 'Don\'t have an account? Register',
      'missing_input': 'Please enter both username and password',
      'invalid_login': 'Invalid username or password',
      'register_title': 'Register',
      'register_btn': 'Sign Up',
      'already_have_account': 'Already have an account? Login',
      'student_role': 'Student',
      'driver_role': 'Driver',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'fill_all_fields': 'Please fill in all fields',
      'password_mismatch': 'Passwords do not match',
      'register_success': 'Registration successful!',
      'register_error': 'Registration failed',
      'username_taken': 'This username is already taken',
      'settings': 'Settings',
      'account': 'Account',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'app_settings': 'App Settings',
      'change_language': 'Language',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'map': 'Map',
      'map_title': 'Bus Location (Map)',
      'schedule': 'Schedule',
      'schedule_title': 'Bus Schedule',
      'report': 'Report Issue',
      'driver_status': 'Status',
      'ticket_report': 'Ticket Report',
      'notifications': 'Alerts',
      'status_ready': 'Ready',
      'status_stop': 'Out of Service',
      'status_maintain': 'Maintenance',
      'status_fuel': 'Refueling',
      'current_status': 'Select current bus status:',
      'save_status': 'Save Status',
      'status_updated': 'Status updated to: ',
      'manage_status': 'Manage Bus Status',
      'alert_queue': 'Queue Alerts',
      'remaining_tickets': 'Select appx. passengers in bus',
      'no_passenger': 'Empty (0-10)',
      'some_passenger': 'Some Seats (11-20)',
      'full_passenger': 'Full (21+)',
      'save_ticket': 'Save Report',
      'ticket_updated': 'Ticket report saved successfully',
      'exact_passenger_count': 'Paper Ticket Count',
      'enter_exact_passenger': 'Enter ticket count (e.g. 45)',
      'driver_name_label': 'Driver',
      'driver_phone_label': 'Phone',
      'license_plate_label': 'Plate',
      'speed_label': 'Speed',
      'route_label': 'Route',
      'time_label': 'Time',
      'bus_label': 'Bus',
      'no_schedule': 'No schedule data available',
      'select_round_time': 'Select driving round',
      'select_round_time_hint': 'Select round time',
      'enter_ticket_count': 'Please enter ticket count',
      'invalid_ticket_count': 'Invalid ticket count',
      'recent_reports': 'Recent Reports',
      'no_reports': 'No reports yet',
      'ticket_count_label': 'Tickets',
      'round_time_label': 'Round',
      'round_passed': 'Passed',
      'time_remaining': 'Time left',
      'minutes': 'min',
      'hours': 'hr',
      'no_bus_assigned': 'No bus assigned yet',
      'test_notification': 'Test Notification',
      'test_notification_body': 'This is a test notification',
      'phone': 'Phone Number',
      'required_field': 'This field is required',
      'profile_saved': 'Profile saved successfully',
      'profile_save_error': 'Failed to save profile',
      'save_profile': 'Save Profile',
      'show_all_rounds': 'Show All Rounds',
      'auto_notification_toggle': 'Auto Notifications',
      'notification_active_desc':
          'You will be notified 15 min before and at departure time',
      'notification_inactive_desc':
          'Enable to receive automatic schedule notifications',
      'notification_info':
          '2 alerts per round: 15 min before & at departure time',
      'depart_now': 'Depart',
      'status_running': 'Running',
      'status_parking': 'Parked',
      'status_at_stop': 'At Stop',
      'status_unknown': 'Unknown',
      'arriving_buses': 'Arriving Buses (Click to view on map)',
      'waiting_tracking': 'Waiting for tracking data...',
      'driver': 'Driver',
      'driver_phone': 'Phone',
      'license_plate_prefix': 'Plate',
      'speed_suffix': 'km/h',
      'sys_status': 'Sys Status',
      'last_updated': 'Last Update',
      'live_count': 'LIVE',
      'schedule_header': 'Shuttle Bus Schedule',
      'campus_name': 'KMUTNB Prachinburi',
      'round': 'Round',
      'responsible_person': 'Responsible Persons',
      'report_issue_title': 'Report an Issue',
      'issue_topic': 'Issue Topic',
      'issue_late': 'Bus is late',
      'issue_driver': 'Driver behavior',
      'issue_app': 'App issue',
      'issue_other': 'Other',
      'select_issue_hint': 'Select an issue',
      'issue_required': 'Please select an issue topic',
      'additional_details': 'Additional Details',
      'details_hint': 'Explain the issue in more detail...',
      'details_required': 'Please enter details',
      'submit_report': 'Submit Report',
      'report_success': 'Report submitted successfully',
      'arrived': 'Arrived',
      'will_arrive_in': 'Will arrive in',
      'stop_short_1': 'Dorm',
      'stop_short_2': 'Entrance',
      'stop_short_3': 'Bus.Ad.',
      'stop_short_4': 'Agro.',
      'stop_short_5': 'Admin',
      'stop_short_6': 'Tech',
      'stop_short_7': 'Eng.',
      'stop_full_1': 'Student Dormitory',
      'stop_full_2': 'Main Entrance',
      'stop_full_3': 'Business Admin',
      'stop_full_4': 'Agro-Industry',
      'stop_full_5': 'Admin Building',
      'stop_full_6': 'Technology',
      'stop_full_7': 'Engineering',
      'driver_prefix': 'Mr.',
      'phone_label_short': 'Tel.',
      'round_label_short': 'Round',
      'next_label_short': 'Next',
      'error_prefix': 'Error',
      'user_inactive': 'Account is inactive or suspended',
      'network_error': 'Network connection issue',
      'permission_denied': 'Could not save data (Permission denied)',
      'view_all_reports': 'View All Reports',
      'show_less_reports': 'Show Less',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'enter_current_password': 'Please enter current password',
      'enter_new_password': 'Please enter new password',
      'enter_confirm_password': 'Please confirm new password',
      'password_min_length': 'Password must be at least 6 characters',
      'password_changed_success': 'Password changed successfully',
      'password_change_error': 'Error changing password',
      'incorrect_current_password': 'Incorrect current password',
      'next_round': 'Next Round',
    },
  };

  static String of(BuildContext context, String key) {
    final locale = Provider.of<LocalizationProvider>(
      context,
      listen: false,
    ).locale;
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static String translateDbStatus(BuildContext context, String status) {
    if (status == 'พร้อมให้บริการ') return of(context, 'status_ready');
    if (status == 'หยุดให้บริการ') return of(context, 'status_stop');
    if (status == 'ซ่อมบำรุง') return of(context, 'status_maintain');
    if (status == 'เติมน้ำมัน') return of(context, 'status_fuel');
    if (status == 'กำลังวิ่ง' ||
        status == 'วิ่งอยู่' ||
        status == 'กำลังเดินทาง')
      return of(context, 'status_running');
    if (status == 'จอดอยู่' || status == 'จอดรอ')
      return of(context, 'status_parking');
    if (status == 'รับส่งตรงป้าย') return of(context, 'status_at_stop');
    if (status == 'ไม่ทราบสถานะ') return of(context, 'status_unknown');
    return status;
  }
}
