import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'localization_provider.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'th': {
      'login_title': 'KMUTNB Shuttle Bus',
      'username': 'รหัสนักศึกษา / รหัสพนักงาน',
      'student_id': 'รหัสนักศึกษา',
      'employee_id': 'รหัสพนักงาน',
      'password': 'รหัสผ่าน',
      'login_btn': 'เข้าสู่ระบบ',
      'no_account': 'ยังไม่มีบัญชีใช่ไหม? สมัครสมาชิกที่นี่',
      'missing_input': 'กรุณากรอกรหัสผู้ใช้และรหัสผ่านให้ครบถ้วน',
      'invalid_login': 'รหัสผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
      'register_title': 'สมัครสมาชิก',
      'register_btn': 'ยืนยันการสมัคร',
      'already_have_account': 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
      'student_role': 'นักศึกษา',
      'driver_role': 'พนักงานขับรถ',
      'full_name': 'ชื่อ-นามสกุล',
      'confirm_password': 'ยืนยันรหัสผ่าน',
      'fill_all_fields': 'กรุณากรอกข้อมูลให้ครบถ้วน',
      'password_mismatch': 'รหัสผ่านไม่ตรงกัน',
      'register_success': 'สมัครสมาชิกสำเร็จ!',
      'register_error': 'เกิดข้อผิดพลาดในการสมัครสมาชิก',
      'username_taken': 'รหัสผู้ใช้นี้ถูกใช้งานแล้ว',
      'settings': 'การตั้งค่า',
      'account': 'บัญชีผู้ใช้',
      'edit_profile': 'แก้ไขข้อมูลส่วนตัว',
      'change_password': 'เปลี่ยนรหัสผ่าน',
      'app_settings': 'ตั้งค่าแอปพลิเคชัน',
      'change_language': 'เปลี่ยนภาษา',
      'dark_mode': 'โหมดกลางคืน (Dark Mode)',
      'logout': 'ออกจากระบบ',
      'map': 'แผนที่',
      'map_title': 'ตำแหน่งรถ (แผนที่)',
      'schedule': 'ตารางรถ',
      'schedule_title': 'ตารางเวลาเดินรถ',
      'report': 'แจ้งปัญหา',
      'driver_status': 'สถานะรถ',
      'ticket_report': 'รายงานตั๋ว',
      'notifications': 'แจ้งเตือน',
      'status_ready': 'พร้อมให้บริการ',
      'status_stop': 'หยุดให้บริการ',
      'status_maintain': 'ซ่อมบำรุง',
      'status_fuel': 'เติมน้ำมัน',
      'current_status': 'เลือกสถานะปัจจุบันของรถบัส:',
      'save_status': 'บันทึกสถานะ',
      'status_updated': 'อัปเดตเป็นสถานะ: ',
      'manage_status': 'จัดการสถานะรถ',
      'alert_queue': 'การแจ้งเตือนรอบรถ',
      'remaining_tickets': 'เลือกจำนวนผู้โดยสารบนรถ (ประมาณ)',
      'no_passenger': 'ว่าง (0-10)',
      'some_passenger': 'พอมีที่นั่ง (11-20)',
      'full_passenger': 'เต็ม/แน่น (21+)',
      'save_ticket': 'บันทึกรายงาน',
      'ticket_updated': 'บันทึกรายงานตั๋วเรียบร้อย',
      'exact_passenger_count': 'จำนวนตั๋วโดยสารที่เก็บได้',
      'enter_exact_passenger': 'กรอกจำนวนตั๋ว (เช่น 45)',
      'driver_name_label': 'คนขับ',
      'driver_phone_label': 'เบอร์โทร',
      'license_plate_label': 'ทะเบียน',
      'speed_label': 'ความเร็ว',
      'route_label': 'เส้นทาง',
      'time_label': 'เวลา',
      'bus_label': 'รถบัส',
      'no_schedule': 'ไม่มีข้อมูลตารางเดินรถ',
      'select_round_time': 'เลือกรอบเวลาที่ขับ',
      'select_round_time_hint': 'เลือกรอบเวลา',
      'enter_ticket_count': 'กรุณากรอกจำนวนตั๋ว',
      'invalid_ticket_count': 'จำนวนตั๋วไม่ถูกต้อง',
      'recent_reports': 'รายงานล่าสุด',
      'no_reports': 'ยังไม่มีรายงาน',
      'ticket_count_label': 'จำนวนตั๋ว',
      'round_time_label': 'รอบเวลา',
      'round_passed': 'ผ่านไปแล้ว',
      'time_remaining': 'เหลือเวลา',
      'minutes': 'นาที',
      'hours': 'ชั่วโมง',
      'no_bus_assigned': 'ยังไม่มีรถที่ถูกกำหนดให้',
      'test_notification': 'ทดสอบแจ้งเตือน',
      'test_notification_body': 'นี่คือข้อความแจ้งเตือนทดสอบ',
      'phone': 'เบอร์โทรศัพท์',
      'required_field': 'กรุณากรอกข้อมูล',
      'profile_saved': 'บันทึกข้อมูลเรียบร้อยแล้ว',
      'profile_save_error': 'เกิดข้อผิดพลาดในการบันทึกข้อมูล',
      'save_profile': 'บันทึกข้อมูล',
      'show_all_rounds': 'ดูทุกรอบ',
    },
    'en': {
      'login_title': 'KMUTNB Shuttle Bus',
      'username': 'Student ID / Employee ID',
      'student_id': 'Student ID',
      'employee_id': 'Employee ID',
      'password': 'Password',
      'login_btn': 'Login',
      'no_account': 'Don\'t have an account? Register',
      'missing_input': 'Please enter both username and password',
      'invalid_login': 'Invalid username or password',
      'register_title': 'Register',
      'register_btn': 'Sign Up',
      'already_have_account': 'Already have an account? Login',
      'student_role': 'Student',
      'driver_role': 'Driver',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'fill_all_fields': 'Please fill in all fields',
      'password_mismatch': 'Passwords do not match',
      'register_success': 'Registration successful!',
      'register_error': 'Registration failed',
      'username_taken': 'This username is already taken',
      'settings': 'Settings',
      'account': 'Account',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'app_settings': 'App Settings',
      'change_language': 'Language',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'map': 'Map',
      'map_title': 'Bus Location (Map)',
      'schedule': 'Schedule',
      'schedule_title': 'Bus Schedule',
      'report': 'Report Issue',
      'driver_status': 'Status',
      'ticket_report': 'Ticket Report',
      'notifications': 'Alerts',
      'status_ready': 'Ready for Service',
      'status_stop': 'Out of Service',
      'status_maintain': 'Maintenance',
      'status_fuel': 'Refueling',
      'current_status': 'Select current bus status:',
      'save_status': 'Save Status',
      'status_updated': 'Status updated to: ',
      'manage_status': 'Manage Bus Status',
      'alert_queue': 'Queue Alerts',
      'remaining_tickets': 'Select appx. passengers in bus',
      'no_passenger': 'Empty (0-10)',
      'some_passenger': 'Some Seats (11-20)',
      'full_passenger': 'Full (21+)',
      'save_ticket': 'Save Report',
      'ticket_updated': 'Ticket report saved successfully',
      'exact_passenger_count': 'Paper Ticket Count',
      'enter_exact_passenger': 'Enter ticket count (e.g. 45)',
      'driver_name_label': 'Driver',
      'driver_phone_label': 'Phone',
      'license_plate_label': 'Plate',
      'speed_label': 'Speed',
      'route_label': 'Route',
      'time_label': 'Time',
      'bus_label': 'Bus',
      'no_schedule': 'No schedule data available',
      'select_round_time': 'Select driving round',
      'select_round_time_hint': 'Select round time',
      'enter_ticket_count': 'Please enter ticket count',
      'invalid_ticket_count': 'Invalid ticket count',
      'recent_reports': 'Recent Reports',
      'no_reports': 'No reports yet',
      'ticket_count_label': 'Tickets',
      'round_time_label': 'Round',
      'round_passed': 'Passed',
      'time_remaining': 'Time left',
      'minutes': 'min',
      'hours': 'hr',
      'no_bus_assigned': 'No bus assigned yet',
      'test_notification': 'Test Notification',
      'test_notification_body': 'This is a test notification',
      'phone': 'Phone Number',
      'required_field': 'This field is required',
      'profile_saved': 'Profile saved successfully',
      'profile_save_error': 'Failed to save profile',
      'save_profile': 'Save Profile',
      'show_all_rounds': 'Show All Rounds',
    },
  };

  static String of(BuildContext context, String key) {
    final locale = Provider.of<LocalizationProvider>(
      context,
      listen: false,
    ).locale;
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}
