// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuKELHOGgZ8YwBIZtuhfNF8Qhq5Ru85to',
    appId: '1:155173650252:web:71f1245f7867408d63d9e9',
    messagingSenderId: '155173650252',
    projectId: 'projectkmutnbbus',
    authDomain: 'projectkmutnbbus.firebaseapp.com',
    storageBucket: 'projectkmutnbbus.firebasestorage.app',
    measurementId: 'G-P05TML00L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaA3qALucoQv1hsiVWb-JcCoZsRAcfj7o',
    appId: '1:155173650252:android:36db716a1a9a4e6063d9e9',
    messagingSenderId: '155173650252',
    projectId: 'projectkmutnbbus',
    storageBucket: 'projectkmutnbbus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjDlGIquVJEpY1oVqOJQeOGFA6NpQh450',
    appId: '1:155173650252:ios:062a4bf57bab4abc63d9e9',
    messagingSenderId: '155173650252',
    projectId: 'projectkmutnbbus',
    storageBucket: 'projectkmutnbbus.firebasestorage.app',
    iosBundleId: 'com.example.kmutnbBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjDlGIquVJEpY1oVqOJQeOGFA6NpQh450',
    appId: '1:155173650252:ios:062a4bf57bab4abc63d9e9',
    messagingSenderId: '155173650252',
    projectId: 'projectkmutnbbus',
    storageBucket: 'projectkmutnbbus.firebasestorage.app',
    iosBundleId: 'com.example.kmutnbBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuKELHOGgZ8YwBIZtuhfNF8Qhq5Ru85to',
    appId: '1:155173650252:web:033a3682c4f2f8cd63d9e9',
    messagingSenderId: '155173650252',
    projectId: 'projectkmutnbbus',
    authDomain: 'projectkmutnbbus.firebaseapp.com',
    storageBucket: 'projectkmutnbbus.firebasestorage.app',
    measurementId: 'G-XW1H864X5K',
  );
}
